var searchData=
[
  ['screen_20entry_0',['Synchronization on Screen Entry',['../protocol_reference.html#autotoc_md71',1,'']]],
  ['screen_20recording_20permission_1',['Issue 2 — macOS client crash after granting Screen Recording permission',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md13',1,'']]],
  ['second_20blocking_20window_20in_20macaudiocapture_3a_3astart_2',['Tertiary note: the 10-second blocking window in &lt;span class=&quot;tt&quot;&gt;MacAudioCapture::start()&lt;/span&gt;',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md18',1,'']]],
  ['secondary_20suspect_3a_20com_20apartment_20mismatch_3',['Secondary suspect: COM apartment mismatch',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md10',1,'']]],
  ['secondary_20suspect_3a_20nsscreencaptureusagedescription_20missing_20from_20info_20plist_4',['Secondary suspect: &lt;span class=&quot;tt&quot;&gt;NSScreenCaptureUsageDescription&lt;/span&gt; missing from Info.plist',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md17',1,'']]],
  ['security_20protocol_20v1_204_5',['TLS Handshake and Security (Protocol v1.4+)',['../protocol_reference.html#autotoc_md67',1,'']]],
  ['sequence_6',['Complete Message Exchange Sequence',['../protocol_reference.html#autotoc_md78',1,'']]],
  ['server_20fixed_7',['Issue 3 — Wrong pitch and clipping on the server (fixed)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md20',1,'']]],
  ['server_20packet_20capture_8',['Step 2 — Simultaneous client + server packet capture',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md4',1,'']]],
  ['session_9',['session',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md39',1,'Setting log level for the debug session'],['../md_docs_2dev_2audio-routing-debug.html#autotoc_md36',1,'Starting a debug session']]],
  ['session_20checklist_10',['Combined debugging session checklist',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md42',1,'']]],
  ['setting_20log_20level_20for_20the_20debug_20session_11',['Setting log level for the debug session',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md39',1,'']]],
  ['settings_12',['How the dev binary finds its settings',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md28',1,'']]],
  ['settings_20file_20via_20the_20gui_13',['One-time setup: write the settings file via the GUI',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md29',1,'']]],
  ['setup_3a_20write_20the_20settings_20file_20via_20the_20gui_14',['One-time setup: write the settings file via the GUI',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md29',1,'']]],
  ['simultaneous_20client_20server_20packet_20capture_15',['Step 2 — Simultaneous client + server packet capture',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md4',1,'']]],
  ['size_20limits_16',['Message and Data Size Limits',['../protocol_reference.html#autotoc_md66',1,'']]],
  ['specific_20implementations_17',['Platform-Specific Implementations',['../protocol_reference.html#autotoc_md82',1,'']]],
  ['starting_20a_20debug_20session_18',['Starting a debug session',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md36',1,'']]],
  ['state_20descriptions_19',['State Descriptions',['../protocol_reference.html#autotoc_md61',1,'']]],
  ['state_20machine_20',['Protocol State Machine',['../protocol_reference.html#autotoc_md60',1,'']]],
  ['step_200_20—_20enable_20verbose_20logging_20on_20both_20machines_21',['Step 0 — Enable verbose logging on both machines',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md2',1,'']]],
  ['step_201_20—_20verify_20the_20audio_20tcp_20channel_20while_20connected_22',['Step 1 — Verify the audio TCP channel while connected',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md3',1,'']]],
  ['step_202_20—_20simultaneous_20client_20server_20packet_20capture_23',['Step 2 — Simultaneous client + server packet capture',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md4',1,'']]],
  ['steps_24',['Diagnostic steps',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md9',1,'']]],
  ['stop_20the_20release_20core_20before_20running_20the_20dev_20binary_25',['Stop the release core before running the dev binary',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md30',1,'']]],
  ['stream_26',['Tertiary note: WASAPI loopback requires an active render stream',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md11',1,'']]],
  ['summary_27',['Architecture summary',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md1',1,'']]],
  ['support_20and_20resources_28',['Support and Resources',['../protocol_reference.html#autotoc_md88',1,'']]],
  ['suspect_3a_20com_20apartment_20mismatch_29',['Secondary suspect: COM apartment mismatch',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md10',1,'']]],
  ['suspect_3a_20nsscreencaptureusagedescription_20missing_20from_20info_20plist_30',['Secondary suspect: &lt;span class=&quot;tt&quot;&gt;NSScreenCaptureUsageDescription&lt;/span&gt; missing from Info.plist',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md17',1,'']]],
  ['symptom_31',['Symptom',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md21',1,'']]],
  ['synchronization_32',['Timing and Synchronization',['../protocol_reference.html#autotoc_md69',1,'']]],
  ['synchronization_20on_20screen_20entry_33',['Synchronization on Screen Entry',['../protocol_reference.html#autotoc_md71',1,'']]],
  ['system_20qt_34',['System Qt',['../md_docs_2dev_2build.html#autotoc_md48',1,'']]]
];
