var searchData=
[
  ['a_20buffer_20overread_20fixed_0',['Root cause: WASAPI format mismatch caused a buffer overread (fixed)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md7',1,'']]],
  ['a_20debug_20binary_1',['Build a debug binary',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md27',1,'']]],
  ['a_20debug_20session_2',['Starting a debug session',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md36',1,'']]],
  ['a_20dev_20build_20repo_20binary_20vs_20release_20peers_3',['Debugging from a dev build (repo binary vs release peers)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md26',1,'']]],
  ['a_20regression_4',['a regression',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md16',1,'Verifying the fix / diagnosing a regression'],['../md_docs_2dev_2audio-routing-debug.html#autotoc_md24',1,'Verifying the fix / diagnosing a regression']]],
  ['accepted_20cli_20flags_20all_20that_20exist_5',['Accepted CLI flags (all that exist)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md32',1,'']]],
  ['active_20render_20stream_6',['Tertiary note: WASAPI loopback requires an active render stream',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md11',1,'']]],
  ['advanced_20features_7',['Advanced Features',['../protocol_reference.html#autotoc_md85',1,'']]],
  ['after_20free_20in_20macaudiocapture_3a_3astart_20—_20file_20compiled_20without_20arc_20fixed_8',['Root cause: use-after-free in &lt;span class=&quot;tt&quot;&gt;MacAudioCapture::start()&lt;/span&gt; — file compiled without ARC (fixed)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md14',1,'']]],
  ['after_20granting_20screen_20recording_20permission_9',['Issue 2 — macOS client crash after granting Screen Recording permission',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md13',1,'']]],
  ['alive_20mechanism_20protocol_20v1_203_10',['Keep-Alive Mechanism (Protocol v1.3+)',['../protocol_reference.html#autotoc_md70',1,'']]],
  ['all_20that_20exist_11',['Accepted CLI flags (all that exist)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md32',1,'']]],
  ['always_20included_12',['&lt;span class=&quot;tt&quot;&gt;--new-instance&lt;/span&gt; is always included',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md38',1,'']]],
  ['an_20active_20render_20stream_13',['Tertiary note: WASAPI loopback requires an active render stream',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md11',1,'']]],
  ['and_20clipping_20on_20the_20server_20fixed_14',['Issue 3 — Wrong pitch and clipping on the server (fixed)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md20',1,'']]],
  ['and_20data_20size_20limits_15',['Message and Data Size Limits',['../protocol_reference.html#autotoc_md66',1,'']]],
  ['and_20modifier_20mapping_16',['Key Code and Modifier Mapping',['../protocol_reference.html#autotoc_md68',1,'']]],
  ['and_20qt_17',['Windows and Qt',['../md_docs_2dev_2build.html#autotoc_md47',1,'']]],
  ['and_20resources_18',['Support and Resources',['../protocol_reference.html#autotoc_md88',1,'']]],
  ['and_20security_20protocol_20v1_204_19',['TLS Handshake and Security (Protocol v1.4+)',['../protocol_reference.html#autotoc_md67',1,'']]],
  ['and_20synchronization_20',['Timing and Synchronization',['../protocol_reference.html#autotoc_md69',1,'']]],
  ['and_20troubleshooting_21',['Debugging and Troubleshooting',['../protocol_reference.html#autotoc_md79',1,'']]],
  ['apartment_20mismatch_22',['Secondary suspect: COM apartment mismatch',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md10',1,'']]],
  ['applied_23',['applied',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md8',1,'Fix applied'],['../md_docs_2dev_2audio-routing-debug.html#autotoc_md15',1,'Fix applied'],['../md_docs_2dev_2audio-routing-debug.html#autotoc_md23',1,'Fix applied']]],
  ['arc_20fixed_24',['Root cause: use-after-free in &lt;span class=&quot;tt&quot;&gt;MacAudioCapture::start()&lt;/span&gt; — file compiled without ARC (fixed)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md14',1,'']]],
  ['architecture_25',['Protocol Architecture',['../protocol_reference.html#autotoc_md59',1,'']]],
  ['architecture_20overview_26',['Architecture Overview',['../index.html#autotoc_md55',1,'']]],
  ['architecture_20summary_27',['Architecture summary',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md1',1,'']]],
  ['audio_20routing_28',['Useful breakpoint locations for audio routing',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md40',1,'']]],
  ['audio_20routing_20—_20debugging_20guide_29',['Audio Routing — Debugging Guide',['../md_docs_2dev_2audio-routing-debug.html',1,'']]],
  ['audio_20tcp_20channel_20while_20connected_30',['Step 1 — Verify the audio TCP channel while connected',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md3',1,'']]]
];
