var searchData=
[
  ['table_0',['Message Reference Table',['../protocol_reference.html#autotoc_md63',1,'']]],
  ['tcp_20channel_20while_20connected_1',['Step 1 — Verify the audio TCP channel while connected',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md3',1,'']]],
  ['tertiary_20note_3a_20the_2010_20second_20blocking_20window_20in_20macaudiocapture_3a_3astart_2',['Tertiary note: the 10-second blocking window in &lt;span class=&quot;tt&quot;&gt;MacAudioCapture::start()&lt;/span&gt;',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md18',1,'']]],
  ['tertiary_20note_3a_20wasapi_20loopback_20requires_20an_20active_20render_20stream_3',['Tertiary note: WASAPI loopback requires an active render stream',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md11',1,'']]],
  ['that_20exist_4',['Accepted CLI flags (all that exist)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md32',1,'']]],
  ['the_2010_20second_20blocking_20window_20in_20macaudiocapture_3a_3astart_5',['Tertiary note: the 10-second blocking window in &lt;span class=&quot;tt&quot;&gt;MacAudioCapture::start()&lt;/span&gt;',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md18',1,'']]],
  ['the_20audio_20tcp_20channel_20while_20connected_6',['Step 1 — Verify the audio TCP channel while connected',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md3',1,'']]],
  ['the_20debug_20session_7',['Setting log level for the debug session',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md39',1,'']]],
  ['the_20dev_20binary_8',['Stop the release core before running the dev binary',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md30',1,'']]],
  ['the_20dev_20binary_20finds_20its_20settings_9',['How the dev binary finds its settings',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md28',1,'']]],
  ['the_20dev_20run_10',['Enable verbose logging for the dev run',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md31',1,'']]],
  ['the_20device_20rate_20fixed_11',['Root cause: the Windows playback path never resampled to the device rate (fixed)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md22',1,'']]],
  ['the_20fix_20diagnosing_20a_20regression_12',['the fix diagnosing a regression',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md16',1,'Verifying the fix / diagnosing a regression'],['../md_docs_2dev_2audio-routing-debug.html#autotoc_md24',1,'Verifying the fix / diagnosing a regression']]],
  ['the_20full_20guidelines_13',['Read the Full Guidelines',['../contributing_guide.html#autotoc_md54',1,'']]],
  ['the_20gui_14',['One-time setup: write the settings file via the GUI',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md29',1,'']]],
  ['the_20release_20core_20before_20running_20the_20dev_20binary_15',['Stop the release core before running the dev binary',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md30',1,'']]],
  ['the_20server_20fixed_16',['Issue 3 — Wrong pitch and clipping on the server (fixed)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md20',1,'']]],
  ['the_20settings_20file_20via_20the_20gui_17',['One-time setup: write the settings file via the GUI',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md29',1,'']]],
  ['the_20windows_20playback_20path_20never_20resampled_20to_20the_20device_20rate_20fixed_18',['Root cause: the Windows playback path never resampled to the device rate (fixed)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md22',1,'']]],
  ['time_20setup_3a_20write_20the_20settings_20file_20via_20the_20gui_19',['One-time setup: write the settings file via the GUI',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md29',1,'']]],
  ['timeout_20',['Handshake Timeout',['../protocol_reference.html#autotoc_md72',1,'']]],
  ['timing_20and_20synchronization_21',['Timing and Synchronization',['../protocol_reference.html#autotoc_md69',1,'']]],
  ['tls_20handshake_20and_20security_20protocol_20v1_204_22',['TLS Handshake and Security (Protocol v1.4+)',['../protocol_reference.html#autotoc_md67',1,'']]],
  ['to_20deskflow_23',['Contributing to Deskflow',['../contributing_guide.html',1,'']]],
  ['to_20the_20device_20rate_20fixed_24',['Root cause: the Windows playback path never resampled to the device rate (fixed)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md22',1,'']]],
  ['tools_25',['Debug Tools',['../protocol_reference.html#autotoc_md81',1,'']]],
  ['troubleshooting_26',['Debugging and Troubleshooting',['../protocol_reference.html#autotoc_md79',1,'']]],
  ['typical_20control_20flow_27',['Typical Control Flow',['../protocol_reference.html#autotoc_md64',1,'']]]
];
