var searchData=
[
  ['capture_0',['Step 2 — Simultaneous client + server packet capture',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md4',1,'']]],
  ['categories_1',['Message Categories',['../protocol_reference.html#autotoc_md62',1,'']]],
  ['cause_3a_20the_20windows_20playback_20path_20never_20resampled_20to_20the_20device_20rate_20fixed_2',['Root cause: the Windows playback path never resampled to the device rate (fixed)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md22',1,'']]],
  ['cause_3a_20use_20after_20free_20in_20macaudiocapture_3a_3astart_20—_20file_20compiled_20without_20arc_20fixed_3',['Root cause: use-after-free in &lt;span class=&quot;tt&quot;&gt;MacAudioCapture::start()&lt;/span&gt; — file compiled without ARC (fixed)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md14',1,'']]],
  ['cause_3a_20wasapi_20format_20mismatch_20caused_20a_20buffer_20overread_20fixed_4',['Root cause: WASAPI format mismatch caused a buffer overread (fixed)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md7',1,'']]],
  ['caused_20a_20buffer_20overread_20fixed_5',['Root cause: WASAPI format mismatch caused a buffer overread (fixed)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md7',1,'']]],
  ['channel_20while_20connected_6',['Step 1 — Verify the audio TCP channel while connected',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md3',1,'']]],
  ['checklist_7',['Implementation Checklist',['../protocol_reference.html#autotoc_md83',1,'']]],
  ['checklist_8',['Combined debugging session checklist',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md42',1,'']]],
  ['cli_20flags_20all_20that_20exist_9',['Accepted CLI flags (all that exist)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md32',1,'']]],
  ['cli_20reference_20for_20deskflow_20core_10',['CLI reference for deskflow-core',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md43',1,'']]],
  ['client_20crash_11',['Issue 1 — Windows client crash',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md6',1,'']]],
  ['client_20crash_20after_20granting_20screen_20recording_20permission_12',['Issue 2 — macOS client crash after granting Screen Recording permission',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md13',1,'']]],
  ['client_20implementation_13',['Basic Client Implementation',['../protocol_reference.html#autotoc_md84',1,'']]],
  ['client_20server_20packet_20capture_14',['Step 2 — Simultaneous client + server packet capture',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md4',1,'']]],
  ['clipping_20on_20the_20server_20fixed_15',['Issue 3 — Wrong pitch and clipping on the server (fixed)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md20',1,'']]],
  ['code_20and_20modifier_20mapping_16',['Key Code and Modifier Mapping',['../protocol_reference.html#autotoc_md68',1,'']]],
  ['codesign_17',['macOS codesign',['../md_docs_2dev_2build.html#autotoc_md50',1,'']]],
  ['com_20apartment_20mismatch_18',['Secondary suspect: COM apartment mismatch',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md10',1,'']]],
  ['combined_20debugging_20session_20checklist_19',['Combined debugging session checklist',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md42',1,'']]],
  ['common_20issues_20',['Common Issues',['../protocol_reference.html#autotoc_md80',1,'']]],
  ['compatibility_21',['Version Compatibility',['../protocol_reference.html#autotoc_md73',1,'']]],
  ['compiled_20without_20arc_20fixed_22',['Root cause: use-after-free in &lt;span class=&quot;tt&quot;&gt;MacAudioCapture::start()&lt;/span&gt; — file compiled without ARC (fixed)',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md14',1,'']]],
  ['complete_20message_20exchange_20sequence_23',['Complete Message Exchange Sequence',['../protocol_reference.html#autotoc_md78',1,'']]],
  ['configuration_24',['Configuration',['../md_docs_2dev_2build.html#autotoc_md45',1,'Configuration'],['../md_docs_2dev_2build.html#autotoc_md46',1,'Windows Configuration']]],
  ['connected_25',['Step 1 — Verify the audio TCP channel while connected',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md3',1,'']]],
  ['connection_20lifecycle_26',['Connection Lifecycle',['../protocol_reference.html#autotoc_md76',1,'']]],
  ['constraints_27',['Protocol Constraints',['../protocol_reference.html#autotoc_md65',1,'']]],
  ['contributing_28',['Contributing',['../protocol_reference.html#autotoc_md87',1,'']]],
  ['contributing_20to_20deskflow_29',['Contributing to Deskflow',['../contributing_guide.html',1,'']]],
  ['control_20flow_30',['Typical Control Flow',['../protocol_reference.html#autotoc_md64',1,'']]],
  ['core_31',['CLI reference for deskflow-core',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md43',1,'']]],
  ['core_20before_20running_20the_20dev_20binary_32',['Stop the release core before running the dev binary',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md30',1,'']]],
  ['crash_33',['Issue 1 — Windows client crash',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md6',1,'']]],
  ['crash_20after_20granting_20screen_20recording_20permission_34',['Issue 2 — macOS client crash after granting Screen Recording permission',['../md_docs_2dev_2audio-routing-debug.html#autotoc_md13',1,'']]]
];
